// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1OQOD3ePsTqDy7y2OIp7xLAOtPL5_j6w',
    appId: '1:1049254927432:web:0c5586149f1bca6a13cc7d',
    messagingSenderId: '1049254927432',
    projectId: 'fandom-verse-techwiz-2026',
    authDomain: 'fandom-verse-techwiz-2026.firebaseapp.com',
    storageBucket: 'fandom-verse-techwiz-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF2UOCyWWUCoytaGfNtAqO35Aj6M_E1KY',
    appId: '1:1049254927432:android:21fe4a464d7ed24013cc7d',
    messagingSenderId: '1049254927432',
    projectId: 'fandom-verse-techwiz-2026',
    storageBucket: 'fandom-verse-techwiz-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxQ0SgvfF7I0UJgrxbZanIYKFYi7htscM',
    appId: '1:1049254927432:ios:7344e8be523ef7c813cc7d',
    messagingSenderId: '1049254927432',
    projectId: 'fandom-verse-techwiz-2026',
    storageBucket: 'fandom-verse-techwiz-2026.firebasestorage.app',
    iosBundleId: 'com.example.fandomVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxQ0SgvfF7I0UJgrxbZanIYKFYi7htscM',
    appId: '1:1049254927432:ios:7344e8be523ef7c813cc7d',
    messagingSenderId: '1049254927432',
    projectId: 'fandom-verse-techwiz-2026',
    storageBucket: 'fandom-verse-techwiz-2026.firebasestorage.app',
    iosBundleId: 'com.example.fandomVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1OQOD3ePsTqDy7y2OIp7xLAOtPL5_j6w',
    appId: '1:1049254927432:web:88cfde4d1b48589313cc7d',
    messagingSenderId: '1049254927432',
    projectId: 'fandom-verse-techwiz-2026',
    authDomain: 'fandom-verse-techwiz-2026.firebaseapp.com',
    storageBucket: 'fandom-verse-techwiz-2026.firebasestorage.app',
  );
}
